[tools]
java = "temurin"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:create-docusaurus" = "latest"
"npm:oclif" = "latest"
"npm:strip-ansi-cli" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
